# Generated by Django 4.0.1 on 2022-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0003_alter_jobskill_job_id_alter_jobskill_skill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='resume',
            field=models.FileField(null=True, upload_to='D:\\Xampp\\htdocs\\django-webproject\\media'),
        ),
    ]
