# Generated by Django 4.0.1 on 2022-02-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0004_alter_seeker_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESUME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user_id', models.IntegerField(null=True)),
                ('resume', models.FileField(null=True, upload_to='D:\\Xampp\\htdocs\\django-webproject\\media')),
            ],
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='resume',
        ),
    ]
