# Generated by Django 4.0.1 on 2022-02-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0005_resume_remove_seeker_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
    ]
