# Generated by Django 4.0.1 on 2022-02-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0008_job_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPLICATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('job_id', models.IntegerField(null=True)),
            ],
        ),
    ]
